apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-agent
  labels:
    app: voice-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-agent
  template:
    metadata:
      labels:
        app: voice-agent
    spec:
      containers:
        - name: voice-agent
          # Use your custom image built via GitHub Actions.
          image: ghcr.io/augius1/assistant-little:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: agents-env
          ports:
            - containerPort: 5000
