apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-agent
  template:
    metadata:
      labels:
        app: voice-agent
    spec:
      containers:
        - name: voice-agent
          image: ghcr.io/augius1/assistant-little:latest
          imagePullPolicy: Always
          # ← add these args to extend the drain so the worker doesn't exit
          args:
            - start
            - --drain-timeout
            - "86400"      # wait up to 24 hours before shutting down
          envFrom:
            - secretRef:
                name: agents-env
          ports:
            - containerPort: 5000
